projects = {
            "GL": {
                "10320": {
                    "name": "API A",
                    "pod": "a-api",
                    "version": "1.1.1",
                    "v_env": "CIT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "10321": {
                    "name": "API B",
                    "pod": "b-api",
                    "version": "1.2.1",
                    "v_env": "CIT",
                    "env": "none",
                    "appd": "false",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "10322": {
                    "name": "API C",
                    "pod": "c-api",
                    "version": "2.1.1",
                    "v_env": "SIT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "false",
                    "last_updated": "3 pm",
                    "running": False
                },
                "10820": {
                    "name": "API D",
                    "pod": "d-api",
                    "version": "1.9.1",
                    "v_env": "VPT",
                    "env": "none",
                    "appd": "false",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "9320": {
                    "name": "API E",
                    "pod": "e-api",
                    "version": "0.1.1",
                    "v_env": "UAT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "9321": {
                    "name": "API E",
                    "pod": "e-api",
                    "version": "0.1.1",
                    "v_env": "UAT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
            },
            "SL": {
                "10320": {
                    "name": "API A",
                    "pod": "a-api",
                    "version": "1.1.1",
                    "v-env": "CIT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": False
                },
                "10321": {
                    "name": "API B",
                    "pod": "b-api",
                    "version": "1.2.1",
                    "v-env": "CIT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": False
                },
                "10322": {
                    "name": "API C",
                    "pod": "c-api",
                    "version": "2.1.1",
                    "v-env": "SIT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "false",
                    "last_updated": "3 pm",
                    "running": True
                },
                "10820": {
                    "name": "API D",
                    "pod": "d-api",
                    "version": "1.9.1",
                    "v-env": "VPT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "9320": {
                    "name": "API E",
                    "pod": "e-api",
                    "version": "0.1.1",
                    "v-env": "UAT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
                "9321": {
                    "name": "API E",
                    "pod": "e-api",
                    "version": "0.1.1",
                    "v_env": "UAT",
                    "env": "none",
                    "appd": "true",
                    "wily": "false",
                    "elk": "true",
                    "last_updated": "2 pm",
                    "running": True
                },
            }
        }